dashboard/urls.py
from django.urls import path
from .views import home, about, help, tips

urlpatterns = [
    path('', home, name="home"),
    path('about/', about, name="about"),
    path('help/', help, name="help"),
    path('tips/', tips, name="tips"),
]

task/urls.py
from django.urls import path
from .views import task, task_detail_view, task_add_view, task_update_view, task_delete_view

app_name = "task"
urlpatterns = [
    path('task_list/', task, name="task-list"),
    path('task-detail-view/<str:pk>', task_detail_view, name="task-detail-view"),
    path('task-add/', task_add_view, name="task-add-view"),
    path('task-update-view/<str:pk>', task_update_view, name="task-update-view"),
    path('task-delete-view/<str:pk>', task_delete_view, name="task-delete-view"),
]

toodoo_application/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/',user_views.register, name='register'),
    path('profile/',user_views.profile, name='profile'),
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', include('dashboard.urls')),
    path('task/', include('task.urls', namespace="task")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models

# Register your models here.

task/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    complete = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True) 
    
    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['complete']
        

users/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')
    
    def __str__(self):
        return f'{self.user.username} Profile'
    
    

task/forms.py
from django import forms
from .models import Task

class TaskFormView(forms.ModelForm):
    class Meta:
        model = Task
        fields = ('title', 'description')

class TaskUpdateForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ('title', 'description', 'complete', 'user')
        exclude = ('user',)

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        
class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()
    
    class Meta:
        model = User
        fields = ['username', 'email']
        
class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

dashboard/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.contrib.auth.decorators import login_required

# Create your views here.

@login_required
def home(request):
    return render(request,'dashboard/home.html')

@login_required
def about(request):
    return render(request,'dashboard/about.html')

@login_required
def help(request):
    return render(request,'dashboard/help.html')

@login_required
def tips(request):
    return render(request,'dashboard/tips.html')

task/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic.list import ListView
from .models import Task, User
from django.contrib.auth.decorators import login_required
from .forms import TaskFormView, TaskUpdateForm
# Create your views here.

@login_required
def task(request):
    tasks = Task.objects.filter(user=request.user)
    context = {
        "tasks": tasks
    }
    return render(request,'task/task_list.html', context)

@login_required
def task_detail_view(request, pk):
    task = get_object_or_404(Task, pk=pk)
    context = {
        "task": task
    }
    return render(request,'task/task_detail.html', context)

@login_required
def task_add_view(request):
    if request.POST:
        form = TaskFormView(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.user = request.user
            task.save()
    else:
        form = TaskFormView()

    context = {
        "form": form
    }
    return render(request,'task/task_add.html', context)


@login_required
def task_update_view(request, pk):
    task = get_object_or_404(Task, pk=pk)
    if request.POST:
        form = TaskUpdateForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
    else:
        form = TaskUpdateForm(instance=task)
            
    context = {
        "form": form
    }
    return render(request,'task/task_update.html', context)

@login_required
def task_delete_view(request, pk):
    task = get_object_or_404(Task, pk=pk)
    task.delete()
    
    return redirect('task:task-list')

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm

def register(request):
    if request.method=='POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, 
                f'Welcome, {username}.')
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request,'users/register.html',{'form':form})

@login_required
def profile(request):
    if request.method=='POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, 
                f'Profile has been updated.')
            return redirect('profile')
            
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }
    
    return render(request, 'users/profile.html', context)

dashboard/templates/dashboard/about.html
<title>About | TooDoo!!!</title>

{% extends 'dashboard/base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'dashboard/about.css' %}">

<!--INSERT ABOUT CONTENT HERE-->
<br>
<div class="aboutheader1">
    <p>
      <img src="{% static "dashboard/images/catt.png" %}" alt="cat" height='150px'>
      📎 About TooDoo!!!. 
    </p>
  </div>
  <br>
<div class="aboutdesc1">
    <p>
        Balancing productivity with well-being can be one of the most important yet challenging 
        elements of starting and maintaining a successful life. Good time management can help 
        us accomplish the right amount of work, stay energized and maximize our 
        career and personal potential.
    </p>
  </div>
  <div class="aboutdesc2">
    <p>
        TooDoo!!! is here to help you plan, organize and accomplish your tasks.
    </p>
  </div>
  <br><br><br><br>
  <div class="aboutheader2">
    <p>
      📎 Meet the Developers.
      <img src="{% static "dashboard/images/catt.png" %}" alt="cat" height='150px'>
    </p>
  </div>
  <br>

  
             

  <br><br>

<div class="aboutdesc3">
  <p>
    Get to know us more and the projects we do.
  </p>
  <div class="row">
    <div class="col-md-10 py-1">
      <div class="mb-5 flex-center">
        <a class ="logoabt" href="https://github.com/Team-Brogrammers-AppDev" target="_blank">
          <img src="{% static "dashboard/images/github.png" %}" alt="github">
        </a>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

dashboard/templates/dashboard/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>TooDoo!!!</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'dashboard/base.css' %}">
    <link rel="stylesheet" href="{% static 'task/task_add.css' %}">
    <link rel="stylesheet" href="{% static 'task/task_update.css' %}">
  </head>

  <body>
      <div id="mySidebar" class="sidebar"> 
          <!--INSERT DIV FOR LOGO HERE-->
        <div class="baselogo">
          <img src="{% static "dashboard/images/toodoologo.png" %}" alt="toodoo logo">
        </div>
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">×</a>
        <a href="{% url 'home' %}">🏠 &nbsp&nbsp Home</a>
        <a href="{% url 'task:task-list' %}">✅ &nbsp&nbsp My TooDoo</a>
        <a href="{% url 'tips' %}">💡 &nbsp&nbsp Tips</a>
        <a href="{% url 'profile' %}">😺 &nbsp&nbsp Profile</a>
        <a href="{% url 'about' %}">📖 &nbsp&nbsp About</a>
        <a href="{% url 'help' %}">❓ &nbsp&nbsp Help</a>
        <br>
        <a href="{% url 'logout' %}">↩️ &nbsp Log Out</a>
      </div>
      
      <div id="main">
        <button class="openbtn" onclick="openNav()">
          ☰ <img src="{% static "dashboard/images/toodoolight.png" %}" alt="toodoo logo">
        </button>  
        <div class="userpic">
        <img height="70px" class="rounded-circle account-img" src="{{ user.profile.image.url }}">
        </div>
        <br><br>
            <div class="container">
              {% if messages %}
                  {% for message in messages %}
                    <div class="alert alert-{{message.tags}}">
                      {{ message }}
                    </div>
                  {% endfor %}
                {% endif %}
                {% block content %}
                {% endblock content %}
            </div>
      </div>

      

      <footer id="sticky-footer" class="flex-shrink-0 py-4 bg-dark text-white-50">
        <div class="container text-center">
          <small>Copyright &copy; 2022 Brogrammers</small>
        </div>
      </footer>

      <script>
      function openNav() {
        document.getElementById("mySidebar").style.width = "250px";
        document.getElementById("main").style.marginLeft = "250px";
      }
      
      function closeNav() {
        document.getElementById("mySidebar").style.width = "0";
        document.getElementById("main").style.marginLeft= "0";
      }
      </script>




    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

dashboard/templates/dashboard/help.html
<title>Help | TooDoo!!!</title>

{% extends 'dashboard/base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'dashboard/help.css' %}">

<!--INSERT HELP CONTENT HERE-->
  <img src="{% static "dashboard/images/catt.png" %}" alt="cat" height='250px'>
<br>
<div class="helpheader">
  <p>
    📎 Do you need help? Do you want to give feedback? 
  </p>
  <p>
    Contact Us.
  </p>
  <div class="row">
    <div class="col-md-10 py-1">
      <div class="mb-5 flex-center">
        <a class ="logohelp" href="https://www.facebook.com/" target="_blank">
          <img src="{% static "dashboard/images/facebook.png" %}" alt="facebook">
        </a>
        <a class ="logohelp" href="https://www.linkedin.com/login" target="_blank">
          <img src="{% static "dashboard/images/linkedin.png" %}" alt="linkedin">
        </a>
        <a class ="logohelp" href="https://www.google.com/intl/fil/gmail/about/" target="_blank">
            <img src="{% static "dashboard/images/gmail.png" %}" alt="gmail">
        </a>
        <a class ="logohelp" href="https://telegram.org/" target="_blank">
            <img src="{% static "dashboard/images/telegram.png" %}" alt="telegram">
        </a>
        <a class ="logohelp" href="https://discord.com/" target="_blank">
            <img src="{% static "dashboard/images/discord.png" %}" alt="discord">
        </a>
      </div>
    </div>
  </div>
</div>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% endblock content %}

dashboard/templates/dashboard/home.html
<title>Home | TooDoo!!!</title>

{% extends 'dashboard/base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'dashboard/home.css' %}">
<!--INSERT HOME CONTENT HERE-->
<br>
<div class="homeheader">
  <p>
    <img src="{% static "dashboard/images/cathi.png" %}" alt="cat" height='100px'>
      Hello {{ user.username }}, let's get organized together.
  </p>
</div>
<br>

<!--Carousel-Home-->
<br>
<div class="caro" >
<div class="container-fluid">
<div id="carouselhome" class="carousel slide" data-bs-ride="carousel" width="100%">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselhome" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselhome" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselhome" data-bs-slide-to="2" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselhome" data-bs-slide-to="3" aria-label="Slide 2"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static "dashboard/images/plan.png" %}" class="d-block w-100" alt="plan">
    </div>
    <div class="carousel-item">
      <img src="{% static "dashboard/images/organize.png" %}" class="d-block w-100" alt="organize">    
    </div>
    <div class="carousel-item">
      <img src="{% static "dashboard/images/accomplish.png" %}" class="d-block w-100" alt="accomplish">    
    </div>
    <div class="carousel-item">
      <img src="{% static "dashboard/images/productive.png" %}" class="d-block w-100" alt="productive">    
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselhome" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselhome" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
</div>
</div>
<br><br><br><br>

<div class="buttons">
  <div class="gitna">
<a href="#CALENDAR" data-bs-toggle="modal" data-bs-target="#CALENDAR">
  <button type="button" class="kalendaryo"> OPEN A CALENDAR </button>
</a>
<a href="{% url 'task:task-list' %}">
  <button type="button" class="gototask"> VIEW TASKS </button>
</a>
<a href="{% url 'task:task-add-view' %}">
  <button type="button" class="gotoadd"> ADD A NEW TASK </button>
</a>
  </div>
</div>

<div class="CALENDAR">
  <div class="modal fade" id="CALENDAR" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <p>TODAY IS <span id='date-time'></span>.</p>
      <button align-items="right" type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <iframe src="https://calendar.google.com/calendar/embed?height=500&wkst=1&bgcolor=%237986CB&ctz=Asia%2FManila&showNav=0&showPrint=0&showTabs=0&showTitle=0&src=emVubi5ncmltbUBnbWFpbC5jb20&src=YWRkcmVzc2Jvb2sjY29udGFjdHNAZ3JvdXAudi5jYWxlbmRhci5nb29nbGUuY29t&src=ZW4ucGhpbGlwcGluZXMjaG9saWRheUBncm91cC52LmNhbGVuZGFyLmdvb2dsZS5jb20&color=%23039BE5&color=%2333B679&color=%230B8043" style="border-width:0" width="1000" height="650" frameborder="0" scrolling="no"></iframe>
      </div>
    </div>
  </div>
</div>
</div>

<script>
  var dt = new Date();
  document.getElementById('date-time').innerHTML=dt;
  </script>


<div class="homedeschead">
  <p>
    ✅ Stay on track and never miss a due date.
  </p>

<div class="homedescription">
<p>
    TooDoo!!! is here to manage and organize your tasks. 
    We will help you plan to do something and get it done 
    to boost your productivity. Let's get organized together!
    <br><br>
</p>
</div>
<br><br><br><br><br>

{% endblock content %}

task/templates/task/task_add.html
<title>Add Task | TooDoo!!!</title>
{% extends 'dashboard/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<!--INSERT ABOUT CONTENT HERE-->
<form method="POST">
    {% csrf_token %}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4 header">
            Task Add
        </legend>
        {{ form|crispy }}
    </fieldset>
    <div class="form-group">
        <button class="btn btn-outline-info" type="submit" id="btnShowMsg" onClick="showMessage()">
            Submit
        </button>  
    </div>

</form>

<script type="text/javascript">
    function showMessage() {
        if(confirm("TASK ADDED SUCCESSFULLY, PLEASE GO BACK TO MY TOODOO PAGE")) {
    window.location.protocol = "http://127.0.0.1:8000/task/task_list/"

    
}
    }
</script>

<br><br><br><br><br><br><br><br>

{% endblock content %}

task/templates/task/task_detail.html
<title>My TooDoo | TooDoo!!!</title>

{% extends 'dashboard/base.html' %}

{% block content %}
<!--INSERT ABOUT CONTENT HERE-->
{% load static %}
<link rel="stylesheet" href="{% static 'task/task_detail.css' %}">

<p> TITLE: {{ task.title }} </p>
<br>
<p> DESCRIPTION: {{ task.description }} </p>
<br>
{% if task.complete %}
    <p class="taskdesc"> STATUS: Task completed. </p>
{% else %}
<p class="taskdesc"> STATUS: Task incomplete. </p>
{% endif %}
<br>
<p> DATE CREATED: {{ task.created }} </p>
<br><br>
<a class="btn-primary" href="{% url 'task:task-update-view' task.pk %}">
    Update Task
</a>
<a class="btn-primary" href="{% url 'task:task-delete-view' task.pk %}">
    Delete Task
</a>

<br><br><br><br><br><br><br><br>


{% endblock content %}

task/templates/task/task_list.html
<title>My TooDoo | TooDoo!!!</title>

{% extends 'dashboard/base.html' %}

{% block content %}
<a class="btn-primary" href="{% url 'task:task-add-view' %}">
   + Add New Task
</a>
<br><br><br>


<!--INSERT ABOUT CONTENT HERE-->
{% load static %}
<link rel="stylesheet" href="{% static 'task/task_list.css' %}">


{% for task in tasks %}

<a href="{% url 'task:task-detail-view' task.pk %}">
   {{ task }} <br>
</a>

{% empty %}
<img src="{% static "dashboard/images/catwords.png" %}" alt="NO TASKS AT THE MOMENT" width="1000px">
{% endfor %}

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>




{% endblock content %}

task/templates/task/task_update.html
<title>Update Task | TooDoo!!!</title>
{% extends 'dashboard/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
<link rel="stylesheet" href="{% static 'task/task_update.css' %}">

{% block content %}
<!--INSERT ABOUT CONTENT HERE-->
<form method="POST">
    {% csrf_token %}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4">
            Update Task.
        </legend>
        {{ form|crispy }}
    </fieldset>
    <div class="form-group">
        <button class="btn btn-outline-info" type="submit" id="btnShowMsg" onClick="showMessage()">
            Update
        </button>
    </div>
</form>

<script type="text/javascript">
    function showMessage() {
        if(confirm("TASK UPDATED SUCCESSFULLY, PLEASE GO BACK TO MY TOODOO PAGE")) {
    window.location.protocol = "http://127.0.0.1:8000/task/task_list/"

    
}
    }
</script>

<br><br><br><br><br><br><br><br><br>


{% endblock content %}

users/templates/users/login.html
<title>Log In | TooDoo!!!</title>

{% extends 'users/parent.html' %}
{% load crispy_forms_tags %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'users/register.css' %}">

<div class="register-container">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">
                Log In.
            </legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">
                Login
            </button>
        </div>
    </form>
    <div class="border-top pt-3">
        <small class="text-muted">
            Don't have a TooDoo!!! account yet?  
            <a class="ml-2" href="{% url 'register' %}">SIGN UP</a>
        </small>
    </div>
</div>


{% endblock content %}

users/templates/users/logout.html
<title>Log Out | TooDoo!!!</title>

{% extends 'users/parent.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'users/logout.css' %}">
    <h2 class="logout-text"> You have been logged out. </h2>
        <div class="border-top pt-3">
            <small class="text-muted">
                <a class="ml-2" href="{% url 'login' %}">Log In Again</a>
            </small>
        </div>
{% endblock content %}

users/templates/users/parent.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>TooDoo!!!</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'users/parent.css' %}">
  </head>

  <body>
    <div class="main">
    <div class="row">
      <div class="column">
        <img class="logo" width="350px" src="{% static "dashboard/images/toodoocaption.png" %}" alt="toodoo logo">
      </div>

      <div class="column">
          {% block content %}
          {% endblock content %}
      </div>
    </div>     

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

users/templates/users/profile.html
<title>Profile | TooDoo!!!</title>

{% extends 'dashboard/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'users/profile.css' %}">

<div class="main">
  <div class="content-section">
    <div class="jumbo">
    <div class="media">
      <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
      <div class="media-body">
        <h2 class="account-heading">{{ user.username }}</h2>
        <p class="text-secondary" color="azure" >{{ user.email }}</p>
      </div>
    </div>
    </div>
      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">
                Profile Information
            </legend>
            {{ u_form|crispy }}
            {{ p_form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">
                Update
            </button>
        </div>
    </form>
  </div>
</div>
<br><br><br><br>

{% endblock content %}

users/templates/users/register.html
<title>Sign Up | TooDoo!!!</title>

{% extends 'users/parent.html' %}
{% load crispy_forms_tags %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'users/register.css' %}">

<div class="register-container">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">
                Sign Up.
            </legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">
                Sign Up
            </button>
        </div>
    </form>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already Have A TooDoo!!! Account? 
            <a class="ml-2" href="{% url 'login' %}">LOGIN</a>
        </small>
    </div>
</div>


{% endblock content %}